"""Centralized training (pooled across all clients).

Builds a combined data.yaml that points at the union of all client image
lists, then trains a single YOLO11 model on the pooled data. This is the
"centralized" upper bound — what you'd get if privacy weren't a constraint
and all clients could share raw images.

The combined data.yaml is constructed at runtime:
  - 'train' is a new image-list file concatenating each client's train list
  - 'val' is each client's val pooled OR the held-out, depending on intent
    (we use each client's local val for the train-time loop; held-out eval
    is done separately after training, same as for isolated)
  - 'names' is taken from the first client's data.yaml (all clients share
    the unified schema, so names are identical across them)

Usage:
    python -m train.train_centralized \\
        --client-yamls work/configs/MOCS_n4000_tier_full_s42.yaml \\
                       work/configs/SODA_n4000_tier_full_s42.yaml \\
                       work/configs/ACID_n4000_tier_full_s42.yaml \\
        --heldout-data-yaml work/configs/CIS_n0_tier_full_s42.yaml \\
        --model-variant yolo11s.yaml \\
        --epochs 50 \\
        --results-path results/exp1_centralized_n4000_s42.json
"""
from __future__ import annotations

import argparse
import json
import logging
import time
from pathlib import Path
from typing import Optional

import yaml as yamllib


logger = logging.getLogger(__name__)


def _load_yaml(path: str | Path) -> dict:
    with open(path) as f:
        return yamllib.safe_load(f)


def _resolve_path_field(yaml_cfg: dict, field: str, yaml_path: Path) -> Path:
    """Resolve a relative path in a data.yaml against its 'path' field."""
    value = yaml_cfg.get(field)
    if value is None:
        raise ValueError(f"Field '{field}' missing in {yaml_path}")
    base = Path(yaml_cfg.get("path", yaml_path.parent))
    p = Path(value)
    return p if p.is_absolute() else (base / p).resolve()


def build_pooled_yaml(
    client_yamls: list[str | Path],
    output_yaml_path: str | Path,
    output_root: str | Path | None = None,
) -> Path:
    """Construct a combined data.yaml pooling 'train' and 'val' image lists.

    Args:
        client_yamls: List of paths to per-client data.yaml files
        output_yaml_path: Where to write the new combined data.yaml
        output_root: Optional 'path:' field for the combined yaml. If None,
            uses the parent directory of output_yaml_path.

    Returns:
        Path to the written combined data.yaml.
    """
    output_yaml_path = Path(output_yaml_path)
    output_yaml_path.parent.mkdir(parents=True, exist_ok=True)
    if output_root is None:
        output_root = output_yaml_path.parent
    output_root = Path(output_root).resolve()

    # Resolve each client's train/val image list
    train_image_paths: list[str] = []
    val_image_paths: list[str] = []
    names = None

    for client_yaml in client_yamls:
        client_yaml = Path(client_yaml)
        cfg = _load_yaml(client_yaml)

        if names is None:
            names = cfg.get("names")

        # Read absolute paths to the train image list
        train_list = _resolve_path_field(cfg, "train", client_yaml)
        if not train_list.exists():
            raise FileNotFoundError(f"{client_yaml}: train list {train_list} not found")
        with open(train_list) as f:
            train_image_paths.extend(line.strip() for line in f if line.strip())

        val_list = _resolve_path_field(cfg, "val", client_yaml)
        if val_list.exists():
            with open(val_list) as f:
                val_image_paths.extend(line.strip() for line in f if line.strip())
        else:
            logger.warning(f"{client_yaml}: val list {val_list} not found, skipping")

    # Write pooled lists
    pooled_train_path = output_root / "pooled_train.txt"
    pooled_val_path = output_root / "pooled_val.txt"
    pooled_train_path.write_text("\n".join(train_image_paths) + "\n")
    pooled_val_path.write_text("\n".join(val_image_paths) + "\n")

    # Write combined yaml
    name_lines = []
    if isinstance(names, dict):
        for k, v in sorted(names.items(), key=lambda kv: int(kv[0])):
            name_lines.append(f"  {k}: {v}")
    elif isinstance(names, list):
        for i, v in enumerate(names):
            name_lines.append(f"  {i}: {v}")

    yaml_text = (
        f"# Auto-generated by train.train_centralized\n"
        f"# pooled from: {[str(p) for p in client_yamls]}\n"
        f"path: {output_root}\n"
        f"train: pooled_train.txt\n"
        f"val: pooled_val.txt\n"
        f"\n"
        f"names:\n" + "\n".join(name_lines) + "\n"
    )
    output_yaml_path.write_text(yaml_text)
    logger.info(
        f"Pooled yaml: {output_yaml_path} "
        f"(train={len(train_image_paths)} images, val={len(val_image_paths)} images)"
    )
    return output_yaml_path


def train_centralized(
    client_yamls: list[str | Path],
    heldout_data_yaml: str | Path,
    model_variant: str = "yolo11s.yaml",
    epochs: int = 50,
    imgsz: int = 640,
    batch: int = 16,
    device: Optional[str] = None,
    work_dir: Optional[str | Path] = None,
    seed: int = 42,
    results_path: Optional[str | Path] = None,
) -> dict:
    """Pool the clients' data, train one model, evaluate on held-out."""
    from ultralytics import YOLO
    from ultralytics.nn.tasks import DetectionModel

    from fl.yolo_client import YOLOClient
    from data_prep.schema import load_schema
    from train.evaluate import evaluate_on_yaml

    if work_dir is None:
        work_dir = Path(f"/tmp/fl_construction/centralized")
    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)

    # Build pooled data.yaml
    pooled_yaml = build_pooled_yaml(
        client_yamls=client_yamls,
        output_yaml_path=work_dir / "pooled_data.yaml",
        output_root=work_dir,
    )

    nc = YOLOClient._infer_nc_from_data_yaml(pooled_yaml)
    logger.info(f"[centralized] Building model {model_variant} with nc={nc}")

    if model_variant.endswith(".yaml"):
        det_model = DetectionModel(cfg=model_variant, nc=nc)
        model = YOLO(model_variant)
        model.model = det_model
    else:
        base_yaml = model_variant.replace(".pt", ".yaml")
        det_model = DetectionModel(cfg=base_yaml, nc=nc)
        pretrained = YOLO(model_variant)
        try:
            det_model.load_state_dict(pretrained.model.state_dict(), strict=False)
        except Exception as e:
            logger.warning(f"Could not transfer pretrained weights: {e}")
        model = YOLO(model_variant)
        model.model = det_model

    # Train
    logger.info(f"[centralized] Starting training: epochs={epochs}")
    t0 = time.time()
    train_kwargs = dict(
        data=str(pooled_yaml),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project=str(work_dir),
        name="train",
        exist_ok=True,
        verbose=False,
        seed=seed,
        plots=False,
        save=True,
    )
    if device is not None:
        train_kwargs["device"] = device
    model.train(**train_kwargs)
    train_secs = time.time() - t0

    # Evaluate on held-out
    schema = load_schema()
    testable_unified = schema.testable_on_heldout("CIS")
    testable_yolo_ids = [schema.to_yolo_id(u) for u in testable_unified]

    logger.info(f"[centralized] Evaluating on pooled val (training distribution)")
    pooled_val_eval = evaluate_on_yaml(
        model=model,
        data_yaml=pooled_yaml,
        imgsz=imgsz,
        batch=batch,
        device=device,
        work_dir=work_dir,
        run_name="eval_pooled",
        testable_yolo_ids=testable_yolo_ids,
    )
    logger.info(
        f"[centralized] Pooled val mAP50={pooled_val_eval['map50']:.4f} "
        f"mAP50-95={pooled_val_eval['map50_95']:.4f}"
    )

    logger.info(f"[centralized] Evaluating on held-out: {heldout_data_yaml}")
    heldout_eval = evaluate_on_yaml(
        model=model,
        data_yaml=heldout_data_yaml,
        imgsz=imgsz,
        batch=batch,
        device=device,
        work_dir=work_dir,
        run_name="eval_heldout",
        testable_yolo_ids=testable_yolo_ids,
    )
    logger.info(
        f"[centralized] Held-out mAP50={heldout_eval['map50']:.4f} "
        f"mAP50-95={heldout_eval['map50_95']:.4f} "
        f"mAP50_testable={heldout_eval.get('map50_testable', 0):.4f}"
    )

    result = {
        "method": "centralized",
        "client_yamls": [str(p) for p in client_yamls],
        "pooled_yaml": str(pooled_yaml),
        "heldout_data_yaml": str(heldout_data_yaml),
        "model_variant": model_variant,
        "nc": nc,
        "epochs": epochs,
        "imgsz": imgsz,
        "batch": batch,
        "seed": seed,
        "train_time_seconds": train_secs,
        "pooled_val_eval": pooled_val_eval,
        "heldout_eval": heldout_eval,
    }

    if results_path is not None:
        results_path = Path(results_path)
        results_path.parent.mkdir(parents=True, exist_ok=True)
        with open(results_path, "w") as f:
            json.dump(result, f, indent=2)
        logger.info(f"[centralized] Wrote results to {results_path}")

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--client-yamls", nargs="+", required=True,
                        help="Paths to per-client data.yaml files to pool")
    parser.add_argument("--heldout-data-yaml", required=True)
    parser.add_argument("--model-variant", default="yolo11s.yaml")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default=None)
    parser.add_argument("--work-dir", default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--results-path", default=None)
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    train_centralized(
        client_yamls=args.client_yamls,
        heldout_data_yaml=args.heldout_data_yaml,
        model_variant=args.model_variant,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        work_dir=args.work_dir,
        seed=args.seed,
        results_path=args.results_path,
    )


if __name__ == "__main__":
    main()
